### ISSUE TITLE
INDEL, Structural Variation in eQTL, sQTL

### ISSUE THREAD

**Issue by Shicheng-Guo** [broadinstitute/gtex-v8#6]
Dear Team, 

I am wondering whether INDEL, CNV and Structural Variation are included in eQTL and sQTL analysis? or only SNPs are included? 

Thanks. 

Shicheng

**Comment by francois-a** [comment]
Hi,
SNPs and indels were included in the core QTL analyses (you can see this in the summary statistics files, since the variants are encoded as `chr_pos_ref_alt_build`). QTLs for SV and STRs were reported in separate studies, in https://www.nature.com/articles/ng.3834 and https://www.nature.com/articles/s41588-019-0521-9.

**Comment by Shicheng-Guo** [comment]
Great. Thanks. eSTRs and eSV can also be donwloaded from GTEx website, correct?  Shicheng

**Comment by francois-a** [comment]
The SV data is available from the [GTEx Portal](https://gtexportal.org/home/datasets), under "GTEx Analysis V6". The STR data is available at http://webstr.ucsd.edu/ (STR calls are on AnVIL/dbGaP).
